services:
  - type: web
    name: portal-proposta
    env: python
    buildCommand: |
      # Instala dependências do backend
      pip install -r backend/requirements.txt
      
      # Instala e builda o frontend
      cd frontend
      npm install
      npm run build
      cd ..
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: NODE_VERSION
        value: 18
